### ISSUE TITLE
Not selecting team.

### ISSUE THREAD

**Issue by ELisaac0** [Tazi0/Core#3]
I've been testing the Framework and everything appers to be normal except the fact that I can't choose any team. And an error pops up in the console saying: 

`SCRIPT ERROR: @Core-main/Server/Player.lua:174: attempt to index a nil value (local 'player').`

Also in the database it appars not to be saving my user in the users table.

I created a scratch default server to test.

![unknown](https://user-images.githubusercontent.com/79944042/114268333-d50cde80-9a00-11eb-8207-5ab29bfb93f4.png)

**Comment by Tazi0** [comment]
Completed with pull request
